# Generated by Django 2.1.1 on 2018-09-25 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setlists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='segue',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
