# Generated by Django 2.0.5 on 2018-05-22 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setlists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='state',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
