# Generated by Django 2.0.5 on 2018-05-23 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setlists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='set_pos',
            field=models.IntegerField(),
        ),
    ]
