# Generated by Django 2.0.5 on 2018-05-23 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setlists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setlists.Set'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='song',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='setlists.Song'),
        ),
        migrations.AlterField(
            model_name='set',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setlists.Show'),
        ),
        migrations.AlterField(
            model_name='show',
            name='venue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='setlists.Venue'),
        ),
    ]
