# Generated by Django 2.0.5 on 2018-05-23 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setlists', '0002_auto_20180523_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='show_key',
        ),
    ]
