# Generated by Django 2.0.5 on 2018-05-18 07:55

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('setlists', '0002_auto_20180518_0147'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='show',
            managers=[
                ('options', django.db.models.manager.Manager()),
            ],
        ),
    ]
