# Generated by Django 2.1.1 on 2018-09-26 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setlists', '0002_auto_20180924_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='segue',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
