# Generated by Django 2.0.5 on 2018-05-23 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setlists', '0002_auto_20180523_0352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='set_pos',
        ),
    ]
