# Generated by Django 2.1.2 on 2018-10-08 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setlists', '0003_auto_20180925_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='segue',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
