# Generated by Django 2.0.5 on 2018-05-24 15:04

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('setlists', '0003_remove_show_show_key'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='song',
            managers=[
                ('filter', django.db.models.manager.Manager()),
            ],
        ),
    ]
