# Generated by Django 2.0.5 on 2018-05-18 21:33

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('setlists', '0003_auto_20180518_0155'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='show',
            managers=[
                ('filter', django.db.models.manager.Manager()),
            ],
        ),
    ]
