# Generated by Django 2.0.5 on 2018-05-23 04:46

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('setlists', '0003_remove_set_set_pos'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='performance',
            managers=[
                ('stats', django.db.models.manager.Manager()),
            ],
        ),
    ]
