# Generated by Django 2.1.2 on 2018-10-08 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setlists', '0004_auto_20181008_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='segue',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
