# Generated by Django 2.0.5 on 2018-05-23 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setlists', '0004_auto_20180523_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='guest',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='performance',
            name='notes',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='performance',
            name='segue',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
