# Generated by Django 2.0.5 on 2018-05-25 15:23

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('setlists', '0004_auto_20180524_0904'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='song',
            managers=[
                ('data', django.db.models.manager.Manager()),
            ],
        ),
    ]
